### ISSUE TITLE
Memory limit exceeded when running tests locally

### ISSUE THREAD

**Issue by roback** [twingly/twingly-search-api-php#2]
PHP default memory limit is 128M on OSX. (Travis seems seems to have the limit set to 1G, so thats why the tests passes there.) The XML parsing in the test makes the memory go above that limit.

I found a way to disable the memory limit when testing by adding the following to the `phpunit.xml` file:

``` xml
<php>
  <ini name="memory_limit" value="-1"/>
</php>
```

**Comment by bearburger** [comment]
Sorry I'm using Debian x32 for tests and test used 81M. Fixed.

**Comment by roback** [comment]
:+1:
