### ISSUE TITLE
Update PHP client to Search API v3 [$50]

### ISSUE THREAD

**Issue by roback** [twingly/twingly-search-api-php#22]
Update the client to use the new [Blog Search API v3](https://developer.twingly.com/resources/search/).

Notable changes from the previous version of the Blog Search API are listed under https://developer.twingly.com/resources/search#changes-from-previous-version.

The ruby client was updated in https://github.com/twingly/twingly-search-api-ruby/pull/65, which can be used as help. Some XML fixtures can also be copied from there if needed.

If possible, try to keep all classes/methods/properties backwards compatible with the previous version of the client by marking methods as deprecated. Similar to what was done in the Ruby client.

**Comment by dentarg** [comment]
If you are considering solving this issue, you might be interested in also solving one or more of the following issues (they also have bounties from https://www.bountysource.com/)

* https://github.com/twingly/twingly-search-api-dotnet/issues/32
* https://github.com/twingly/twingly-search-api-java/issues/29
* https://github.com/twingly/twingly-search-api-python/issues/31

**Comment by dentarg** [comment]
@bearburger interested in the bounty here? :)

**Comment by bearburger** [comment]
@dentarg sure, if you can wait till the weekend.

**Comment by dentarg** [comment]
@bearburger sure
