### ISSUE TITLE
Packagist documentation

### ISSUE THREAD

**Issue by dentarg** [twingly/twingly-search-api-php#5]
Hi @bearburger, you wrote earlier (via Upwork) 

> Release on Packagist tested

do you mind writing down the steps for that in the README?

**Comment by bearburger** [comment]
Hi @dentarg 

Actually I'm not sure what to write in it as it is extremely simple. You just [submit new package](https://packagist.org/packages/submit) and that's it. Development version is available as `dev-master` right from the start and if you want to add proper versions you just create `tag` in git (release in terms of Github I think) with version number and then users will be able to choose version in their `composer.json`.

I think if you use GUI client for Git all steps could be done in 3-4 mouse clicks :-)

**Comment by dentarg** [comment]
@bearburger oh that's cool :) I thought it was more like rubygems or pypi, thanks for explaining :)

**Comment by bearburger** [comment]
@dentarg this is for PHP coders it can't be complicated :-D
