### ISSUE TITLE
Publish to Packagist

### ISSUE THREAD

**Issue by dentarg** [twingly/twingly-search-api-php#8]
It's explained in #5 how to do it (I have created an account for it, see 1Password)

Before we do it we should remove https://github.com/twingly/twingly-search-api-php/releases/tag/1.0.0 which points to https://github.com/twingly/twingly-search-api-php/commit/ac4cd1b14418870e636fe0e2fa32df25e6c0cd74

**Comment by roback** [comment]
> Before we do it we should remove https://github.com/twingly/twingly-search-api-php/releases/tag/1.0.0 which points to ac4cd1b

I have done that now so anyone that has cloned this repo needs to remove the tag locally (`git tag -d 1.0.0`)

ping @twingly/dev

**Comment by roback** [comment]
Packagist has a service hook for GitHub which we can use: https://packagist.org/about#how-to-update-packages

**Comment by dentarg** [comment]
> I have done that now so anyone that has cloned this repo needs to remove the tag locally (git tag -d 1.0.0)

Thanks, I've done it

**Comment by roback** [comment]
1.0.0 released!

https://packagist.org/packages/twingly/twingly-search
